 create table cursos (
       id integer generated by default as identity,
        descricao varchar(500),
        nome varchar(100) not null,
        primary key (id)
    );

    insert into cursos(nome,descricao) values
    ('Desenvolvimento de Sistema Multiplataforma',null),
    ('Sistema para Internet',null),
    ('Gestão Empresarial',null);